version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: "3.1-bullseye"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      - elasticsearch
    command: sleep infinity
    network_mode: service:db
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      ELASTICSEARCH_URL: http://elasticsearch:9200/

  elasticsearch:
    build:
      context: ..
      dockerfile: docker/es/Dockerfile
    ports:
      - 9200:9200
    privileged: true
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    logging:
      driver: none
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
